version: "3"
services:  
  payament-api:
    build: "./payament"
    container_name: payament-api
    networks:
      - api-network
    environment:
      - PORT=3000
    ports:
      - 3000:3000

networks:
  api-network:
    driver: bridge
